<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-BR" xml:lang="pt-BR"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Daniel de Freitas e Marcos Vinicius">

<title>Relatório da Catapulta</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-4d7f0bce1131f3e5f9547cd857cfbfc8.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="99">
    <h2 id="toc-title">Índice</h2>
   
  <ul>
  <li><a href="#relatório-de-experimento-estatística-e-probabilidade-com-catapulta" id="toc-relatório-de-experimento-estatística-e-probabilidade-com-catapulta" class="nav-link active" data-scroll-target="#relatório-de-experimento-estatística-e-probabilidade-com-catapulta"><span class="header-section-number">1</span> Relatório de Experimento: Estatística e Probabilidade com Catapulta</a></li>
  <li><a href="#introdução" id="toc-introdução" class="nav-link" data-scroll-target="#introdução"><span class="header-section-number">2</span> Introdução</a></li>
  <li><a href="#metodologia-e-prática-experimental" id="toc-metodologia-e-prática-experimental" class="nav-link" data-scroll-target="#metodologia-e-prática-experimental"><span class="header-section-number">3</span> Metodologia e Prática Experimental</a>
  <ul class="collapse">
  <li><a href="#fatores-controlados" id="toc-fatores-controlados" class="nav-link" data-scroll-target="#fatores-controlados"><span class="header-section-number">3.1</span> Fatores Controlados</a></li>
  </ul></li>
  <li><a href="#configuração-utilizada" id="toc-configuração-utilizada" class="nav-link" data-scroll-target="#configuração-utilizada"><span class="header-section-number">4</span> Configuração Utilizada</a></li>
  <li><a href="#coleta-de-dados" id="toc-coleta-de-dados" class="nav-link" data-scroll-target="#coleta-de-dados"><span class="header-section-number">5</span> Coleta de Dados</a>
  <ul class="collapse">
  <li><a href="#ordenação-de-dados-rol" id="toc-ordenação-de-dados-rol" class="nav-link" data-scroll-target="#ordenação-de-dados-rol"><span class="header-section-number">5.1</span> Ordenação de Dados (Rol)</a></li>
  </ul></li>
  <li><a href="#análise-da-variabilidade-e-aprendizado" id="toc-análise-da-variabilidade-e-aprendizado" class="nav-link" data-scroll-target="#análise-da-variabilidade-e-aprendizado"><span class="header-section-number">6</span> Análise da Variabilidade e Aprendizado</a></li>
  <li><a href="#medidas-estatísticas" id="toc-medidas-estatísticas" class="nav-link" data-scroll-target="#medidas-estatísticas"><span class="header-section-number">7</span> Medidas Estatísticas</a></li>
  <li><a href="#identificação-de-valores-atípicos" id="toc-identificação-de-valores-atípicos" class="nav-link" data-scroll-target="#identificação-de-valores-atípicos"><span class="header-section-number">8</span> Identificação de Valores Atípicos</a></li>
  <li><a href="#conclusões-estatísticas" id="toc-conclusões-estatísticas" class="nav-link" data-scroll-target="#conclusões-estatísticas"><span class="header-section-number">9</span> Conclusões Estatísticas</a></li>
  <li><a href="#aplicação-do-pacote-leem-r-na-análise-de-dados" id="toc-aplicação-do-pacote-leem-r-na-análise-de-dados" class="nav-link" data-scroll-target="#aplicação-do-pacote-leem-r-na-análise-de-dados"><span class="header-section-number">10</span> Aplicação do Pacote <code>leem</code> (R) na Análise de Dados</a>
  <ul class="collapse">
  <li><a href="#exemplos-de-aplicação-do-leem" id="toc-exemplos-de-aplicação-do-leem" class="nav-link" data-scroll-target="#exemplos-de-aplicação-do-leem"><span class="header-section-number">10.1</span> Exemplos de Aplicação do <code>leem</code></a></li>
  <li><a href="#principais-resultados-numéricos" id="toc-principais-resultados-numéricos" class="nav-link" data-scroll-target="#principais-resultados-numéricos"><span class="header-section-number">10.2</span> Principais Resultados Numéricos</a></li>
  <li><a href="#discussão-dos-resultados" id="toc-discussão-dos-resultados" class="nav-link" data-scroll-target="#discussão-dos-resultados"><span class="header-section-number">10.3</span> Discussão dos Resultados</a></li>
  <li><a href="#análise-de-dados" id="toc-análise-de-dados" class="nav-link" data-scroll-target="#análise-de-dados"><span class="header-section-number">10.4</span> Análise de Dados</a></li>
  </ul></li>
  <li><a href="#considerações-finais" id="toc-considerações-finais" class="nav-link" data-scroll-target="#considerações-finais"><span class="header-section-number">11</span> 🧠 Considerações finais</a></li>
  <li><a href="#aprenda-quarto" id="toc-aprenda-quarto" class="nav-link" data-scroll-target="#aprenda-quarto"><span class="header-section-number">12</span> Aprenda Quarto</a></li>
  <li><a href="#referências" id="toc-referências" class="nav-link" data-scroll-target="#referências"><span class="header-section-number">13</span> 📖 Referências</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">
<div class="logos" style="display: flex; justify-content: center; align-items: center; height: 200px; gap: 20px;">
  <a href="https://ufsj.edu.br">
    <img src="imagens/ufsj.png" width="220px">
  </a>
  <a href="https://ufsj.edu.br/defim">
    <img src="imagens/defim.png" width="220px">
  </a>
</div>

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Relatório da Catapulta</h1>
<p class="subtitle lead"><a href="https://bendeivide.github.io/courses/epaec/" target="_blank">Estatística e Probabilidade</a> <br> <a href="https://bendeivide.github.io" target="_blank">Prof.&nbsp;Ben Dêivide (DEFIM/CAP/UFSJ)</a></p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor</div>
    <div class="quarto-title-meta-contents">
             <p>Daniel de Freitas e Marcos Vinicius </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Data de Publicação</div>
    <div class="quarto-title-meta-contents">
      <p class="date">03/04/2026, 15:24</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="relatório-de-experimento-estatística-e-probabilidade-com-catapulta" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="relatório-de-experimento-estatística-e-probabilidade-com-catapulta"><span class="header-section-number">1</span> Relatório de Experimento: Estatística e Probabilidade com Catapulta</h2>
</section>
<section id="introdução" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="introdução"><span class="header-section-number">2</span> Introdução</h2>
<p>Este relatório apresenta de forma detalhada um experimento prático realizado no âmbito da disciplina de Estatística e Probabilidade da UFSJ, com foco na análise de dados coletados a partir de lançamentos de uma catapulta. O objetivo central foi analisar a variabilidade dos resultados de lançamento sob configurações fixas e aplicar técnicas de análise estatística para interpretar os dados obtidos.</p>
</section>
<section id="metodologia-e-prática-experimental" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metodologia-e-prática-experimental"><span class="header-section-number">3</span> Metodologia e Prática Experimental</h2>
<p>O experimento da catapulta funciona como uma base prática para a coleta de dados reais e a aplicação de técnicas de análise estatística. A catapulta utilizada no experimento possibilita o controle de diferentes fatores que influenciam o lançamento, como a tensão do elástico, o ângulo de disparo e o apoio estrutural.</p>
<section id="fatores-controlados" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="fatores-controlados"><span class="header-section-number">3.1</span> Fatores Controlados</h3>
<p>Ao longo do experimento, os seguintes fatores foram controlados para garantir a consistência e permitir a análise da variabilidade:</p>
<ul>
<li><strong>Tensão do Elástico (Posição A)</strong>: Controla a força e a velocidade inicial do projétil.</li>
<li><strong>Ângulo de Disparo (Posição B)</strong>: Define o tempo de voo e o alcance horizontal do projétil.</li>
<li><strong>Apoio Estrutural (Posição O)</strong>: Garante a estabilidade e a geometria do movimento da catapulta.</li>
</ul>
</section>
</section>
<section id="configuração-utilizada" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="configuração-utilizada"><span class="header-section-number">4</span> Configuração Utilizada</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="catapulta.png" class="img-fluid figure-img" style="width:40.0%"></p>
<figcaption>Catapulta utilizada em sala</figcaption>
</figure>
</div>
<p>Para a realização dos lançamentos, uma configuração específica foi mantida constante na catapulta:</p>
<ul>
<li><strong>Posição O-</strong>: Nível 2</li>
<li><strong>Posição A+</strong>: Nível 3</li>
<li><strong>Posição B+</strong>: 90°</li>
<li><strong>Posição A-</strong>: Nível 4</li>
</ul>
</section>
<section id="coleta-de-dados" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="coleta-de-dados"><span class="header-section-number">5</span> Coleta de Dados</h2>
<p>Realizaram-se 22 lançamentos sob as configurações fixas mencionadas. Apesar da manutenção das mesmas configurações, foram obtidas diferentes distâncias de lançamento. Essa variação observada é um aspecto importante para a análise estatística, pois permite identificar e discutir os fatores que contribuem para a dispersão dos resultados.</p>
<section id="ordenação-de-dados-rol" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="ordenação-de-dados-rol"><span class="header-section-number">5.1</span> Ordenação de Dados (Rol)</h3>
<p>Para tornar a análise estatística mais clara, os dados brutos coletados foram organizados em um <strong>rol</strong>, que é a disposição dos valores em ordem crescente. Essa organização inicial é crucial para a visualização da distribuição dos dados e para o cálculo de medidas de posição como a mediana e os quartis.</p>
<p><strong>Dados brutos cm:</strong> <code>326.0, 294.8, 296.8, 294.0, 295.8, 298.5, 300.6, 285.1, 287.1, 292.3, 290.8, 287.9, 282.9, 285.3, 281.5, 278.4, 276.4, 281.7, 277.1, 285.3, 277.1, 281.8</code></p>
<p><strong>Rol em cm:</strong> <code>276.4, 277.1, 277.1, 278.4, 281.5, 281.7, 281.8, 282.9, 285.1, 285.3, 285.3, 287.1, 287.9, 290.8, 292.3, 294.0, 294.8, 295.8, 296.8, 298.5, 300.6, 326.0</code></p>
</section>
</section>
<section id="análise-da-variabilidade-e-aprendizado" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="análise-da-variabilidade-e-aprendizado"><span class="header-section-number">6</span> Análise da Variabilidade e Aprendizado</h2>
<p>A constatação de resultados diferentes, mesmo com configurações fixas, ressalta a importância da estatística na compreensão de fenômenos com variabilidade inerente. Os principais fatores que podem ter contribuído para essa variabilidade incluem:</p>
<ul>
<li>Pequenas modificações na execução de cada lançamento.</li>
<li>Influência de fatores ambientais não controláveis, como correntes de ar.</li>
<li>Limitações e variações nos instrumentos utilizados, como a elasticidade do elástico ao longo do tempo.</li>
</ul>
</section>
<section id="medidas-estatísticas" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="medidas-estatísticas"><span class="header-section-number">7</span> Medidas Estatísticas</h2>
<p>Para a análise dos dados coletados, as seguintes medidas estatísticas foram calculadas:</p>
<ul>
<li><strong>Média</strong>: 288.96 cm. Representa o ponto central em torno do qual os dados se concentram.</li>
<li><strong>Mediana</strong>: 286.20 cm. Indica o valor central dos dados, sendo menos sensível a valores extremos.</li>
<li><strong>Desvio Padrão</strong>: 11.07 cm. Mede a dispersão ou variação dos dados em relação à média.</li>
<li><strong>Mínimo</strong>: 276.40 cm.</li>
<li><strong>Máximo</strong>: 326.00 cm.</li>
<li><strong>Amplitude</strong>: 49.60 cm.</li>
</ul>
<p>Essas medidas são importantes para compreender a distribuição dos lançamentos e facilitar as análises estatísticas subsequentes.</p>
</section>
<section id="identificação-de-valores-atípicos" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="identificação-de-valores-atípicos"><span class="header-section-number">8</span> Identificação de Valores Atípicos</h2>
<p>Ao longo do experimento, a ocorrência de alguns valores de lançamento significativamente maiores ou menores que os demais foi observada. Através da análise de quartis e do Intervalo Interquartil (IQR), foi identificado um valor atípico: <strong>326.0 cm</strong>. Este valor excede o limite superior calculado (Q3 + 1.5 * IQR).</p>
<p>Esse valor atípico pode ter ocorrido por:</p>
<ul>
<li>Erros na execução do lançamento da catapulta.</li>
<li>Variações na deformação do elástico, resultando em maior ou menor força aplicada.</li>
<li>Variações ambientais pontuais que afetaram um lançamento específico.</li>
</ul>
<p>A identificação e análise desses valores atípicos são importantes para entender a robustez do experimento e a influência de fatores não previstos.</p>
</section>
<section id="conclusões-estatísticas" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="conclusões-estatísticas"><span class="header-section-number">9</span> Conclusões Estatísticas</h2>
<p>A partir dos dados obtidos e nas análises estatísticas, diversas conclusões podem ser inferidas sobre o experimento da catapulta:</p>
<ul>
<li><strong>Variabilidade Inerente</strong>: Mesmo sob condições controladas, a variabilidade nos resultados de lançamento é uma característica intrínseca do experimento, reforçando a necessidade de métodos estatísticos para sua compreensão.</li>
<li><strong>Distribuição dos Dados</strong>: A análise da distribuição dos alcances (por exemplo, através de histogramas e boxplots) pode revelar se os dados seguem uma distribuição normal ou outra forma, o que é crucial para a escolha de testes estatísticos apropriados.</li>
<li><strong>Impacto dos Fatores Controlados</strong>: Através de análises de variância (ANOVA) ou testes t, é possível determinar se as diferentes configurações dos fatores controlados (tensão, ângulo, apoio) têm um impacto estatisticamente significativo no alcance médio dos lançamentos.</li>
<li><strong>Correlação e Regressão</strong>: Se variáveis adicionais forem coletadas, análises de correlação e regressão podem identificar relações entre essas variáveis e o alcance, permitindo a construção de modelos preditivos para o desempenho da catapulta.</li>
<li><strong>Controle de Qualidade</strong>: O experimento serve como um excelente exemplo para ilustrar conceitos de controle estatístico de processo (CEP), onde gráficos de controle podem ser utilizados para monitorar a estabilidade do processo de lançamento ao longo do tempo.</li>
<li><strong>Robustez do Experimento</strong>: A presença de valores atípicos, embora desafiadora, oferece uma oportunidade para discutir a robustez das medidas estatísticas e a importância da identificação e tratamento de <em>outliers</em>.</li>
</ul>
<p>De modo geral, o experimento da catapulta não apenas demonstra os princípios fundamentais da estatística descritiva e inferencial, mas também serve como uma plataforma prática para explorar a complexidade da variabilidade em sistemas reais e a aplicação de ferramentas estatísticas para extrair conhecimento significativo dos dados.</p>
</section>
<section id="aplicação-do-pacote-leem-r-na-análise-de-dados" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="aplicação-do-pacote-leem-r-na-análise-de-dados"><span class="header-section-number">10</span> Aplicação do Pacote <code>leem</code> (R) na Análise de Dados</h2>
<p>Para realizar a análise estatística dos dados obtidos no experimento da catapulta, o pacote <code>leem</code> (Laboratório de Ensino de Estatística e Matemática), desenvolvido pelo Prof.&nbsp;Ben Dêivide da UFSJ, oferece um conjunto de ferramentas didáticas e funcionais em linguagem R. Este pacote é particularmente útil para o ensino e a prática de estatística, permitindo a exploração de conceitos de forma interativa e visual.</p>
<section id="exemplos-de-aplicação-do-leem" class="level3" data-number="10.1">
<h3 data-number="10.1" class="anchored" data-anchor-id="exemplos-de-aplicação-do-leem"><span class="header-section-number">10.1</span> Exemplos de Aplicação do <code>leem</code></h3>
<p>Com os dados brutos do experimento agora disponíveis, a aplicação do <code>leem</code> pode seguir os seguintes passos gerais:</p>
<ol type="1">
<li><strong>Importação e Organização dos Dados</strong>: Os dados de alcance dos lançamentos seriam importados para o ambiente R. O <code>leem</code> pode auxiliar na criação de objetos de dados estruturados para facilitar a análise.</li>
<li><strong>Cálculo de Medidas Descritivas</strong>: Utilizar funções do <code>leem</code> para calcular rapidamente a média, mediana, desvio padrão, variância, quartis e outras medidas descritivas dos alcances. Isso forneceria um resumo quantitativo da performance da catapulta.</li>
<li><strong>Visualização de Dados</strong>: O pacote <code>leem</code> permite a criação de gráficos estatísticos essenciais, como histogramas, boxplots e gráficos de dispersão. Essas visualizações são cruciais para entender a distribuição dos dados, identificar valores atípicos e observar padrões.
<ul>
<li><strong>Histograma</strong>: Para visualizar a frequência dos diferentes alcances e a forma da distribuição.</li>
<li><strong>Boxplot</strong>: Para identificar a mediana, quartis e a presença de <em>outliers</em> de forma clara.</li>
</ul></li>
<li><strong>Análise de Variabilidade</strong>: Explorar a variabilidade dos lançamentos, possivelmente comparando diferentes configurações (se houvesse mais de uma) ou analisando a consistência ao longo do tempo. O <code>leem</code> pode oferecer funções para testes de hipóteses simples ou análises de variância, se aplicável.</li>
<li><strong>Simulações e Modelagem</strong>: Para um estudo mais avançado, o <code>leem</code> pode ser empregado em simulações para entender o comportamento probabilístico dos lançamentos ou para construir modelos simples que relacionem os fatores controlados com o alcance.</li>
</ol>
<p>O uso do <code>leem</code> no contexto deste experimento reforça a importância da computação estatística como uma ferramenta poderosa para a análise de dados reais, permitindo que os estudantes apliquem conceitos teóricos em um cenário prático e obtenham <em>insights</em> significativos sobre a variabilidade e o desempenho da catapulta.</p>
</section>
<section id="principais-resultados-numéricos" class="level3" data-number="10.2">
<h3 data-number="10.2" class="anchored" data-anchor-id="principais-resultados-numéricos"><span class="header-section-number">10.2</span> Principais Resultados Numéricos</h3>
<p>A tabela a seguir resume as principais medidas estatísticas calculadas para os alcances dos lançamentos:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Medida Estatística</th>
<th style="text-align: left;">Valor (cm)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Média</td>
<td style="text-align: left;">288.96</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mediana</td>
<td style="text-align: left;">286.20</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Desvio Padrão</td>
<td style="text-align: left;">11.07</td>
</tr>
<tr class="even">
<td style="text-align: left;">Variância</td>
<td style="text-align: left;">122.57</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mínimo</td>
<td style="text-align: left;">276.40</td>
</tr>
<tr class="even">
<td style="text-align: left;">Máximo</td>
<td style="text-align: left;">326.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Amplitude</td>
<td style="text-align: left;">49.60</td>
</tr>
<tr class="even">
<td style="text-align: left;">Primeiro Quartil (Q1)</td>
<td style="text-align: left;">281.73</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Terceiro Quartil (Q3)</td>
<td style="text-align: left;">294.60</td>
</tr>
<tr class="even">
<td style="text-align: left;">Intervalo Interquartil (IQR)</td>
<td style="text-align: left;">12.88</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Limite Superior para Outliers</td>
<td style="text-align: left;">313.91</td>
</tr>
<tr class="even">
<td style="text-align: left;">Coeficiente de Variação (CV)</td>
<td style="text-align: left;">3.83%</td>
</tr>
</tbody>
</table>
<p>A <strong>média</strong> de 288.96 cm indica o valor central dos alcances, enquanto a <strong>mediana</strong> de 286.20 cm, ligeiramente menor, sugere uma possível assimetria à direita na distribuição dos dados, influenciada por valores mais altos. O <strong>desvio padrão</strong> de 11.07 cm e o <strong>coeficiente de variação</strong> de 3.83% indicam uma variabilidade relativamente baixa, mas presente, nos lançamentos, o que é esperado em experimentos físicos mesmo sob condições controladas.</p>
</section>
<section id="discussão-dos-resultados" class="level3" data-number="10.3">
<h3 data-number="10.3" class="anchored" data-anchor-id="discussão-dos-resultados"><span class="header-section-number">10.3</span> Discussão dos Resultados</h3>
<p>Os resultados obtidos estão em grande parte de acordo com o esperado para um experimento físico controlado, mas sujeito a variabilidades inerentes. A presença de uma <strong>grande variabilidade</strong>, evidenciada pelo desvio padrão e pela amplitude, significa que, mesmo com a configuração fixa da catapulta, os lançamentos não são perfeitamente replicáveis. Isso é um conceito fundamental em estatística: a variabilidade é uma característica intrínseca de qualquer processo real [1].</p>
<p>Os fatores que podem ter influenciado esses resultados e as possíveis fontes de erro experimental incluem:</p>
<ul>
<li><strong>Variações na Execução</strong>: Pequenas diferenças na forma como o operador armava ou liberava a catapulta em cada lançamento podem introduzir variabilidade. A precisão humana é limitada e pode levar a pequenas inconsistências [4].</li>
<li><strong>Fatores Ambientais</strong>: Correntes de ar, mesmo que sutis, podem afetar a trajetória do projétil. Embora o experimento tenha sido realizado em sala, microclimas ou movimentos de ar podem ter tido impacto [5].</li>
<li><strong>Limitações dos Instrumentos</strong>: A elasticidade do elástico pode ter variado ligeiramente ao longo dos 22 lançamentos devido à fadiga do material. Além disso, a precisão da medição do alcance pode ter pequenas margens de erro [7].</li>
<li><strong>Outlier</strong>: O valor de 326.0 cm é um outlier significativo. Sua ocorrência pode ser atribuída a um erro de medição, uma anomalia na liberação da catapulta, ou uma interação inesperada com o ambiente. A decisão de incluir ou excluir outliers da análise depende do contexto e do impacto que eles têm nas conclusões. Neste caso, ele destaca a imprevisibilidade pontual do sistema.</li>
</ul>
<p>A distribuição dos dados, embora com uma leve assimetria, não apresenta uma tendência clara de desvio para um lado específico, exceto pelo outlier. A interpretação desses dados reforça a necessidade de múltiplas repetições em experimentos para obter uma estimativa robusta da média e da variabilidade, e para identificar a presença de eventos incomuns.</p>
</section>
<section id="análise-de-dados" class="level3" data-number="10.4">
<h3 data-number="10.4" class="anchored" data-anchor-id="análise-de-dados"><span class="header-section-number">10.4</span> Análise de Dados</h3>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>dados_catapulta <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">326.0</span>, <span class="fl">294.8</span>, <span class="fl">296.8</span>, <span class="fl">294.0</span>, <span class="fl">295.8</span>, <span class="fl">298.5</span>, <span class="fl">300.6</span>, <span class="fl">285.1</span>, <span class="fl">287.1</span>, <span class="fl">292.3</span>, <span class="fl">290.8</span>, <span class="fl">287.9</span>, <span class="fl">282.9</span>, <span class="fl">285.3</span>, <span class="fl">281.5</span>, <span class="fl">278.4</span>, <span class="fl">276.4</span>, <span class="fl">281.7</span>, <span class="fl">277.1</span>, <span class="fl">285.3</span>, <span class="fl">277.1</span>, <span class="fl">281.8</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Para o relatório, podemos usar funções básicas do R para replicar as medidas</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># descritivas e garantir a reprodutibilidade da análise.</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Média</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>media_r <span class="ot">&lt;-</span> <span class="fu">mean</span>(dados_catapulta)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Mediana</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>mediana_r <span class="ot">&lt;-</span> <span class="fu">median</span>(dados_catapulta)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Desvio Padrão (amostral)</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>desvio_padrao_r <span class="ot">&lt;-</span> <span class="fu">sd</span>(dados_catapulta)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Mínimo e Máximo</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>minimo_r <span class="ot">&lt;-</span> <span class="fu">min</span>(dados_catapulta)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>maximo_r <span class="ot">&lt;-</span> <span class="fu">max</span>(dados_catapulta)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Quartis</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>quartis_r <span class="ot">&lt;-</span> <span class="fu">quantile</span>(dados_catapulta, <span class="at">probs =</span> <span class="fu">c</span>(<span class="fl">0.25</span>, <span class="fl">0.75</span>))</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>q1_r <span class="ot">&lt;-</span> quartis_r[<span class="dv">1</span>]</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>q3_r <span class="ot">&lt;-</span> quartis_r[<span class="dv">2</span>]</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Imprimir os resultados (opcional, para verificação)</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">--- Estatística Descritiva (R) ---</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Média: %.2f</span><span class="sc">\n</span><span class="st">"</span>, media_r))</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Mediana: %.2f</span><span class="sc">\n</span><span class="st">"</span>, mediana_r))</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Desvio Padrão: %.2f</span><span class="sc">\n</span><span class="st">"</span>, desvio_padrao_r))</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Mínimo: %.2f</span><span class="sc">\n</span><span class="st">"</span>, minimo_r))</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Máximo: %.2f</span><span class="sc">\n</span><span class="st">"</span>, maximo_r))</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Q1: %.2f</span><span class="sc">\n</span><span class="st">"</span>, q1_r))</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Q3: %.2f</span><span class="sc">\n</span><span class="st">"</span>, q3_r))</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a><span class="co"># Geração de gráficos em R (exemplo para Quarto)</span></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a><span class="co"># Histograma</span></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(dados_catapulta, <span class="at">main =</span> <span class="st">"Distribuição dos Alcances da Catapulta"</span>,</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Alcance (cm)"</span>, <span class="at">ylab =</span> <span class="st">"Frequência"</span>, <span class="at">col =</span> <span class="st">"skyblue"</span>, <span class="at">border =</span> <span class="st">"white"</span>)</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a><span class="co"># Boxplot</span></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(dados_catapulta, <span class="at">main =</span> <span class="st">"Boxplot dos Alcances"</span>,</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Alcance (cm)"</span>, <span class="at">col =</span> <span class="st">"lightgreen"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</section>
</section>
<section id="considerações-finais" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="considerações-finais"><span class="header-section-number">11</span> 🧠 Considerações finais</h2>
<p>O experimento da catapulta, embora simples em sua concepção, revelou-se uma ferramenta didática poderosa para a compreensão de conceitos fundamentais em Estatística e Probabilidade. O objetivo de analisar a variabilidade dos lançamentos sob uma configuração fixa foi plenamente alcançado. Através da coleta de 22 dados e da subsequente análise estatística, foi possível quantificar a dispersão dos resultados e identificar fatores que contribuem para essa variabilidade.</p>
<p>Os principais aprendizados incluem a constatação de que, mesmo em condições aparentemente controladas, a variabilidade é uma característica intrínseca de processos físicos. A análise de medidas descritivas como média, mediana e desvio padrão, juntamente com a visualização gráfica por meio de histogramas e boxplots, permitiu uma interpretação aprofundada do comportamento dos dados. A identificação de um valor atípico ressaltou a importância de investigar eventos incomuns e suas possíveis causas, como erros de execução ou influências ambientais pontuais.</p>
<p>A qualidade dos dados coletados foi satisfatória para os propósitos da análise, embora a presença do outlier indique a necessidade de rigor ainda maior na execução ou na padronização do equipamento. Para futuras melhorias no procedimento experimental, sugere-se a utilização de um mecanismo de lançamento mais automatizado para reduzir a variabilidade humana, a implementação de sensores mais precisos para medição do alcance e a realização do experimento em um ambiente mais controlado para minimizar a influência de fatores externos como o vento. Além disso, a coleta de um número maior de lançamentos poderia proporcionar uma base de dados mais robusta para análises mais avançadas, como testes de hipóteses sobre a normalidade da distribuição ou a comparação entre diferentes configurações da catapulta.</p>
</section>
<section id="aprenda-quarto" class="level2" data-number="12">
<h2 data-number="12" class="anchored" data-anchor-id="aprenda-quarto"><span class="header-section-number">12</span> Aprenda Quarto</h2>
<p>Acesse <a href="https://quarto.org/">Quarto</a>.</p>
</section>
<section id="referências" class="level2" data-number="13">
<h2 data-number="13" class="anchored" data-anchor-id="referências"><span class="header-section-number">13</span> 📖 Referências</h2>
<ul>
<li>[1] Bendeivide. <strong>Estatística e Probabilidade (UFSJ)</strong>. Disponível em: <a href="http://bendeivide.github.io/courses/epaec/" class="uri">http://bendeivide.github.io/courses/epaec/</a>.</li>
<li>[2] Bendeivide. <strong>Modelo de Relatório</strong>. Disponível em: <a href="http://bendeivide.github.io/courses/epaec/modrel/" class="uri">http://bendeivide.github.io/courses/epaec/modrel/</a>.</li>
<li>[3] Bendeivide. <strong>Relatórios da Disciplina Estatística Experimental (UFSJ)</strong>. Disponível em: <a href="https://bendeivide.github.io/relatorio-estprob/relatorio/index.html#vis%C3%A3o-geral-sobre-os-relat%C3%B3rios" class="uri">https://bendeivide.github.io/relatorio-estprob/relatorio/index.html#vis%C3%A3o-geral-sobre-os-relat%C3%B3rios</a>.</li>
<li>[4] Bendeivide. <strong>Pacote <code>leem</code> (Laboratório de Ensino de Estatística e Matemática)</strong>. Disponível em: <a href="https://bendeivide.github.io/leem/" class="uri">https://bendeivide.github.io/leem/</a>.</li>
<li>[5] Bendeivide. <strong>Experimentos para as aulas práticas</strong>. Dísponivel em: <a href="https://bendeivide.github.io/courses/epaec/normal2026.1/#experimentos" class="uri">https://bendeivide.github.io/courses/epaec/normal2026.1/#experimentos</a>.</li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




<script src="index_files/libs/quarto-html/zenscroll-min.js"></script>
</body></html>